### ISSUE TITLE
Default minimum polling interval

### ISSUE THREAD

**Issue by alexsorokoletov** [ealsur/WebJobs.Extensions.GroupQueueTrigger#1]
Big thanks for this project!

Wondering, what is the default value for `MinQueuePollingInterval`?

Comment says it's 2 seconds, but value type is `int` and noted as it's in minutes.

https://github.com/ealsur/WebJobs.Extensions.GroupQueueTrigger/blob/master/Microsoft.Azure.WebJobs.Extensions.GroupQueueTrigger/GroupQueueTriggerAttribute.cs#L76

**Comment by ealsur** [comment]
@alexsorokoletov If specified (ie you assign a value) it's in minutes. 

If not, it [defaults to the Azure QueueTrigger minimum polling interval](https://github.com/ealsur/WebJobs.Extensions.GroupQueueTrigger/blob/master/Microsoft.Azure.WebJobs.Extensions.GroupQueueTrigger/GroupQueueTriggerAttributeBindingProvider.cs#L257), which was 2 seconds, until [they lowered to 100ms](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueuePollingIntervals.cs).

Thanks for finding it, I will update the text :)
