### ISSUE TITLE
Nuget Builds are failing for recent versions

### ISSUE THREAD

**Issue by koverda** [ealsur/WebJobs.Extensions.GroupQueueTrigger#2]
you please fix the nuget build fail? The latest version on nuget is v1.0.9, while the repository is up to v1.0.12.

Thank you.

**Comment by ealsur** [comment]
@koverda Just updated Nuget, the versioning in GitHub was broken due to a linked account with MyGet that was failing.

Updated to 2.0 migrating to Webjobs 2.0 dependency.
