### ISSUE TITLE
BrokeredMessage Support

### ISSUE THREAD

**Issue by jbw521** [ealsur/WebJobs.Extensions.GroupQueueTrigger#4]
I see from your readme and some of the comments in code that only POCO triggers are supported. In our program, we've run into issues caused by long processing times that have forced us to manually renew the message lock every so often, which means we need pull our messages in as BrokeredMessages. 

Did you ever have any luck with getting this to work/have plans to add this feature? Any advice that we could use in our implementation would be appreciated.

**Comment by ealsur** [comment]
Hi @jbw521 , this extension was made for Storage Queues, not Service Bus Queues. Doesn't BrokeredMessages exist only on Service Bus Queues?

**Comment by jbw521** [comment]
Yes, makes sense. Thanks for the response.
