### ISSUE TITLE
What is meaning of 1 MinPooling and Max Pooling Interval

### ISSUE THREAD

**Issue by sandipbhavsar** [ealsur/WebJobs.Extensions.GroupQueueTrigger#5]
Can I give Pooling in seconds

**Comment by ealsur** [comment]
Comments on the attributes explain each one 😄  
https://github.com/ealsur/WebJobs.Extensions.GroupQueueTrigger/blob/master/Microsoft.Azure.WebJobs.Extensions.GroupQueueTrigger/GroupQueueTriggerAttribute.cs
